local buf_nnoremap = require("tt.nvim_utils").keys.buf_nnoremap

buf_nnoremap({"ge", function()
	vim.diagnostic.open_float(0, { scope = "cursor" })
end})
buf_nnoremap({"gd", vim.lsp.buf.definition})
buf_nnoremap({"gt", vim.lsp.buf.type_definition})
buf_nnoremap({"K", vim.lsp.buf.hover})
buf_nnoremap({"[e", vim.diagnostic.goto_next})
buf_nnoremap({"]e", vim.diagnostic.goto_prev})
buf_nnoremap({"ga", vim.lsp.buf.code_action})
buf_nnoremap({"gs", "vsplit|lua vim.lsp.buf.definition"})
buf_nnoremap({"<leader>r", vim.lsp.buf.references})
buf_nnoremap({"<leader>i", vim.lsp.buf.implementation})
buf_nnoremap({"<leader>f", vim.lsp.buf.formatting})
buf_nnoremap({"<leader>n", vim.lsp.buf.rename})
