local iabbrev = require("tt.nvim_utils").vim_util.iabbrev

iabbrev("from", "FROM", true)
iabbrev("run", "RUN", true)
iabbrev("cmd", "CMD", true)
iabbrev("label", "LABEL", true)
iabbrev("env", "ENV", true)
iabbrev("expose", "EXPOSE", true)
iabbrev("add", "ADD", true)
iabbrev("copy", "COPY", true)
iabbrev("entrypoint", "ENTRYPOINT", true)
iabbrev("user", "USER", true)
iabbrev("arg", "ARG", true)
iabbrev("onbuild", "ONBUILD", true)
iabbrev("stopsignal", "STOPSIGNAL", true)
iabbrev("healthcheck", "HEALTHCHECK", true)
iabbrev("shell", "SHELL", true)
iabbrev("volume", "VOLUME", true)
