iabbrev from FROM
iabbrev run RUN
iabbrev cmd CMD
iabbrev label LABEL
iabbrev env ENV
iabbrev expose EXPOSE
iabbrev add ADD
iabbrev copy COPY
iabbrev entrypoint ENTRYPOINT
iabbrev user USER
iabbrev arg ARG
iabbrev onbuild ONBUILD
iabbrev stopsignal STOPSIGNAL
iabbrev healthcheck HEALTHCHECK
iabbrev shell SHELL
iabbrev volume VOLUME
