iabbrev <buffer> from FROM
iabbrev <buffer> run RUN
iabbrev <buffer> cmd CMD
iabbrev <buffer> label LABEL
iabbrev <buffer> env ENV
iabbrev <buffer> expose EXPOSE
iabbrev <buffer> add ADD
iabbrev <buffer> copy COPY
iabbrev <buffer> entrypoint ENTRYPOINT
iabbrev <buffer> user USER
iabbrev <buffer> arg ARG
iabbrev <buffer> onbuild ONBUILD
iabbrev <buffer> stopsignal STOPSIGNAL
iabbrev <buffer> healthcheck HEALTHCHECK
iabbrev <buffer> shell SHELL
iabbrev <buffer> volume VOLUME
