local tools = require("tt.tools")
local git = require("tt.git")
-- INSERT MODE
vim.keymap.set("i", "jj", "<Esc>")
vim.keymap.set("i", "<C-T>", "<C-X><C-]>")
vim.keymap.set("i", "<C-F>", "<C-X><C-F>")
vim.keymap.set("i", "<C-D>", "<C-X><C-D>")
vim.keymap.set("i", "<C-L>", "<C-X><C-L>")

-- TERMINAL MODE
vim.keymap.set("t", "<Esc>", "<C-\\><C-n>")

-- NORMAL MODE
vim.keymap.set("n", "<up>", ":m .-2<cr>==", { silent = true })
vim.keymap.set("n", "<down>", ":m .+1<cr>==", { silent = true })
vim.keymap.set("n", "'", "`")
vim.keymap.set("n", "<leader>p", '"+p')
vim.keymap.set("n", "<leader>P", '"+P')
vim.keymap.set("n", "g.", '/\\V\\C<C-r>"<CR>cgn<C-a><Esc>')
vim.keymap.set("n", "z/", ":let @/='\\<<C-R>=expand(\"<cword>\")<CR>\\>'<CR>:set hls<CR>", { silent = true })

vim.keymap.set("n", "<leader>e", ":e <C-R>=expand('%:p:h') . '/'<CR>")
vim.keymap.set("n", "<C-J>", function()
	tools.winMove("j")
end)
vim.keymap.set("n", "<C-L>", function()
	tools.winMove("l")
end)
vim.keymap.set("n", "<C-H>", function()
	tools.winMove("h")
end)
vim.keymap.set("n", "<C-K>", function()
	tools.winMove("k")
end)
vim.keymap.set("n", "<C-S>", function()
	vim.cmd("tabnew|te")
	vim.api.nvim_input("a")
end)
vim.keymap.set("n", "ssb", tools.sourceSession)
vim.keymap.set("n", "<F1>", tools.profile)
vim.keymap.set("n", "<Esc>", function()
	vim.cmd("nohls")
end)
vim.keymap.set("n", "<leader>B", git.blame_file)
vim.keymap.set("n", "<leader>b", git.blame)
vim.keymap.set("n", "<leader>d", function()
	tools.openTerminalDrawer()
end)

vim.keymap.set("n", "-", function()
	require("oil").open()
end, { silent = true })

vim.keymap.set("n", "<leader>a", function()
	vim.cmd("argadd %")
	vim.cmd("argdedupe")
end, { silent = true })

vim.keymap.set("n", "<leader>1", function()
	vim.cmd("silent! 1argument")
end, { silent = true })

vim.keymap.set("n", "<leader>2", function()
	vim.cmd("silent! 2argument")
end, { silent = true })

vim.keymap.set("n", "<leader>3", function()
	vim.cmd("silent! 3argument")
end, { silent = true })

vim.keymap.set("n", "cc", vim.cmd.cclose, { silent = true })
vim.keymap.set("n", "cl", vim.cmd.lclose, { silent = true })
vim.keymap.set("n", "<leader>h", function()
	require("tt.tools").switchSourceHeader()
end, { silent = true })
vim.keymap.set("n", "<leader>m", ":make<CR>")
vim.keymap.set("n", "<leader>-", '<Cmd>let @+ = expand("%")<CR>', { silent = true })
vim.keymap.set("n", "<F7>", '<Cmd>so "%"<CR>', { silent = true })

vim.keymap.set("n", "S", ":%s//g<LEFT><LEFT>")
vim.keymap.set("n", "g_", ":g//#<Left><Left><C-R><C-W><CR>:")
vim.keymap.set("n", "<C-f>", ":silent grep!<space>")

-- VISUAL MODE
vim.keymap.set("x", "<leader>y", '"+y')
vim.keymap.set("x", "<leader>d", '"+d')
-- Don't trash current register when pasting in visual mode
vim.keymap.set("x", "p", "p:if v:register == '\"'<Bar>let @@=@0<Bar>endif<cr>")
vim.keymap.set("x", "I", "(mode()=~#'[vV]'?'<C-v>^o^I':'I')", { expr = true })
vim.keymap.set("x", "A", "(mode()=~#'[vV]'?'<C-v>0o$A':'A')", { expr = true })
vim.keymap.set("v", "<up>", ":m '<-2<cr>gv=gv")
vim.keymap.set("v", "<down>", ":m '>+1<cr>gv=gv")
-- vim.keymap.set("v", "s", ":s//g<LEFT><LEFT>")
vim.keymap.set("x", "<leader>b", "<Cmd>Gblame<CR>", { silent = true })
