vim.cmd("hi Comment guifg=#f4118e")
-- vim.cmd("hi Function gui=bold guifg=#83a598")
-- vim.cmd("hi @function.method gui=bold guifg=#83a598")
-- vim.cmd("hi Type guifg=#ffaf00")
vim.cmd("hi link TreesitterContext Pmenu")
-- vim.cmd("hi @tag guifg=#ffaf00")
-- vim.cmd("hi @string guifg=#9dbf5f")
vim.cmd("hi Pmenu guifg=#ebdbb2 guibg=#504945")
-- vim.cmd("hi PmenuSel guifg=#504945 guibg=#83a598")
-- vim.cmd("hi PmenuMatch gui=bold guifg=none guibg=none")
-- vim.cmd("hi PmenuMatchSel gui=bold guifg=none guibg=none")
