-- vim.cmd("hi Function gui=bold guifg=#83a598")
-- vim.cmd("hi @function.method gui=bold guifg=#83a598")
-- vim.cmd("hi Type guifg=#ffaf00")
vim.cmd("hi link TreesitterContext Pmenu")
-- vim.cmd("hi @tag guifg=#ffaf00")
-- vim.cmd("hi @string guifg=#9dbf5f")
-- DarkMode:
-- vim.cmd("hi Pmenu guifg=#ebdbb2 guibg=#504945")
-- vim.cmd("hi Comment guifg=#f4118e")
-- vim.cmd("hi PmenuSel guifg=#504945 guibg=#83a598")
-- vim.cmd("hi PmenuMatch gui=bold guifg=none guibg=none")
-- vim.cmd("hi PmenuMatchSel gui=bold guifg=none guibg=none")
-- LightMode
vim.cmd("hi Pmenu guifg=#000000 guibg=white")
vim.cmd("hi! link PmenuSel Visual")
vim.cmd("hi PmenuMatch guifg=#a52a2a guibg=#b2b2b2")
vim.cmd("hi Comment guifg=#0000ff")
vim.cmd("hi LineNr guifg=#4f4f4f")
vim.cmd("hi Cursor gui=none guifg=#e4e4e4 guibg=#2e8b57")
vim.cmd("hi DiagnosticHint guifg=green")
vim.cmd("hi DiagnosticUnderlineHint guisp=green")
